### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by EdwinLauMack** [Nicholas264/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - Missing keystrokes count
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

Great job! I like how you created a script to edit, copy and run the file in your remote server. All you need to address is the keystrokes count and you should be good to go!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by nick-ls** [comment]
I've edited the file to include the number of keystrokes it takes (only 3 since it's a keybind) to build and run the files on the server. Is this what the issue was?

**Comment by EdwinLauMack** [comment]
Hello Nicholas, yes that is what the issue was, I have closed your regrade request and you should be good to go! Please let me know if you have any other questions
